set SLACK_API_TOKEN=xoxp-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
set SLACK_UPLOAD_FILE_TYPE=zips,pdfs,images

echo 削除するターゲット：%SLACK_FILE_DEL_TARGET_CHANNEL%%SLACK_FILE_DEL_TARGET_MAIL%
echo 何日以前削除：%SLACK_FILE_DEL_TARGET_DATE%日
echo 削除するファイルの種類：%SLACK_UPLOAD_FILE_TYPE%

node app/index.js

rem PAUSE